<?php
/** @var \FireGento\WebapiMetrics\Block\Routes $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div class="dashboard-diagram">
    <?php if ($block->hasStatistics()) : ?>
        <div class="dashboard-diagram-image">
            <img src="<?= $escaper->escapeUrl($block->getChartUrl()) ?>" class="dashboard-diagram-chart" alt="Chart"
                 title="Chart"/>
        </div>
    <?php else : ?>
        <div class="dashboard-diagram-nodata">
            <span><?= $escaper->escapeHtml(__('No Data Found')) ?></span>
        </div>
    <?php endif; ?>
</div>
